spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&userSSL=false
    initialization-mode: never
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    club.p9j7: DEBUG
    us.codecraft.webmagic: DEBUG