#!/bin/sh
source ../config/env.sh
db=duwenzheng
tb=sina_seg_result

$HIVE -e "
use $db;
CREATE TABLE $tb(
id string,
title string,
newsTime string,
content string
)
comment 'SinaNews content table'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n'
STORED AS textfile;"
